%Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
%By starting with 1 and 2, the first 10 terms will be:

%1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%By considering the terms in the Fibonacci sequence whose values do not 
%exceed four million, find the sum of the even-valued terms.

%The two first terms are 1 and 2.
v=[1 2 0];
ii=3;

%We use the equation: F(n)=F(n-2)+F(n-1).
while (v(ii-2)+v(ii-1))<4000000
    v(ii)=v(ii-2)+v(ii-1);
    ii=ii+1;
end

%Then we find the sum of the even-valued terms.
%An even number is when a number divided by 2 has no remainder.
%For example 2/2=1 and 8/2=4.

even_v=zeros(size(v));
clear ii
%We use the remainder function to make a vector with the even terms.
for ii=1:length(v)
    if rem(v(ii),2)==0
        even_v(ii)=v(ii);
    else
    end
end
%We then use the disp function to print the sum of the even terms.
disp(sum(even_v))

%% Another way to do it
clear
x = [1 1];
i = 2;
while x(end) < 4*10^(6)
i = i + 1;
x(i) = x(i-1) + x(i-2);
end
x(end) = [];
disp(x(end))

sum(x(find(rem(x,2) == 0)))
